// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVw4k4sHc1O_bwq99JbzGLzgaK-zZNNsg',
    appId: '1:1053739920197:web:92a8cdeba9236d8e96ec2c',
    messagingSenderId: '1053739920197',
    projectId: 'myshop-73804',
    authDomain: 'myshop-73804.firebaseapp.com',
    storageBucket: 'myshop-73804.firebasestorage.app',
    measurementId: 'G-JJLTMG9BQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOeo9ocKesCXGFhCnOTcRMsJ0uQuwvL38',
    appId: '1:1053739920197:android:3dd55ca813e0277396ec2c',
    messagingSenderId: '1053739920197',
    projectId: 'myshop-73804',
    storageBucket: 'myshop-73804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBILm_jsI-DelkNg4wwBxcNwZcD02t28MI',
    appId: '1:1053739920197:ios:4a5dc351a9cb449a96ec2c',
    messagingSenderId: '1053739920197',
    projectId: 'myshop-73804',
    storageBucket: 'myshop-73804.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBILm_jsI-DelkNg4wwBxcNwZcD02t28MI',
    appId: '1:1053739920197:ios:4a5dc351a9cb449a96ec2c',
    messagingSenderId: '1053739920197',
    projectId: 'myshop-73804',
    storageBucket: 'myshop-73804.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVw4k4sHc1O_bwq99JbzGLzgaK-zZNNsg',
    appId: '1:1053739920197:web:bd5ce5e0a93ff74696ec2c',
    messagingSenderId: '1053739920197',
    projectId: 'myshop-73804',
    authDomain: 'myshop-73804.firebaseapp.com',
    storageBucket: 'myshop-73804.firebasestorage.app',
    measurementId: 'G-93BX4681FH',
  );
}
